import { Router } from 'express';
import healthRoutes from './health/index.js';
import authRoutes from './auth/index.js';
import dashboardRoutes from './dashboard/index.js';
import feedbackRoutes from './feedback/index.js';
import organizationRoutes from './organization/index.js';
import organizationSettingsRoutes from './organization/settingsRoutes.js';
import locationRoutes from './organization/locationRoutes.js';
import buildingRoutes from './organization/buildingRoutes.js';
import serviceTypeRoutes from './organization/serviceTypeRoutes.js';
import personnelRoutes from './personnel/index.js';
import tabletsRoutes from './tablets/index.js';
import surveysRoutes from './surveys/index.js';
import questionsRoutes from './surveys/questionRoutes.js';
import reportsRoutes from './reports/index.js';
import analyticsRoutes from './analytics/index.js';
import notificationRoutes from './notifications/index.js';
import settingsRoutes from './settings/index.js';
import auditRoutes from './audit/index.js';
import mobileRoutes from './mobile/index.js';
import serviceSessionsRoutes from './serviceSessions/index.js';
import liveMonitoringRoutes from './live-monitoring/index.js';
import developerPortalRoutes from './developer-portal/index.js';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/organization', organizationSettingsRoutes);
router.use('/departments', organizationRoutes);
router.use('/locations', locationRoutes);
router.use('/buildings', buildingRoutes);
router.use('/service-types', serviceTypeRoutes);
router.use('/personnel', personnelRoutes);
router.use('/tablets', tabletsRoutes);
router.use('/surveys', surveysRoutes);
router.use('/questions', questionsRoutes);
router.use('/reports', reportsRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/notifications', notificationRoutes);
router.use('/settings', settingsRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/mobile', mobileRoutes);
router.use('/service-sessions', serviceSessionsRoutes);
router.use('/live-monitoring', liveMonitoringRoutes);
router.use('/developer-portal', developerPortalRoutes);

export default router;
